### ISSUE TITLE
Support go.mod with tag prefixed with `v`

### ISSUE THREAD

**Issue by sayboras** [tommy-muehle/go-mnd#1]
Hi,

I just noticed that the tag in this repo is not prefixed with `v`, so I am having the below issue

go: github.com/tommy-muehle/go-mnd@v1.1.1: reading github.com/tommy-muehle/go-mnd/go.mod at revision v1.1.1: unknown revision v1.1.1

Let me know if you have any plan to tag with `v` prefix (e.g. v1.1.1)

**Comment by tommy-muehle** [comment]
Hi @sayboras,
sorry for the late answer. I have added all prefixed tags. Also the releases are updated now.

**Comment by tommy-muehle** [comment]
Thanks for the hint!

**Comment by sayboras** [comment]
@tommy-muehle thanks for your help :100: 

I can use the go.mod version with this repo now
