### ISSUE TITLE
need a way to ignore numbers in certain functions

### ISSUE THREAD

**Issue by viktorasm** [tommy-muehle/go-mnd#10]
Sometimes it does not make sense to externalize a magic number when it's usage is completely obvious, e.g. builder pattern:

```
config := aws.NewConfig().WithMaxRetries(30)
```

or converters
```
config.MaxRetries = aws.Int(30)
```

semantically, these numbers should be treated like assignments.

**Comment by olvlvl** [comment]
Could we add `wg.Add(1)` to the list?

**Comment by tommy-muehle** [comment]
@viktorasm Thanks for the report. Should be easy to implement.

**Comment by valer-cara** [comment]
@tommy-muehle - do you have a suggestion for the approach?

I'm imagining passing a list of ignored functions using their "fully qualified" name, similar to [errcheck](https://github.com/kisielk/errcheck#excluding-functions). Eg:

```
-ignored-functions="(*github.com/aws/aws-sdk-go.Config).MaxRetries"
```

The downside with this approach is that there's no type resolution at the AST level, so one needs much more complex parsing of the package tree to allow resolving an AST node to it's full name, again refering to [errcheck](https://github.com/kisielk/errcheck/blob/master/internal/errcheck/errcheck.go#L320)

Do you see a cheaper way of identifying these ignorables? (not sure if i'm way off here)

**Comment by tommy-muehle** [comment]
@valer-cara I solved this by using regexp patterns. In this way we're very flexible.
