### ISSUE TITLE
Go modules v2 compatibility

### ISSUE THREAD

**Issue by invidian** [tommy-muehle/go-mnd#15]
### Short summary 

As latest released version at the time of writing is `v2.2.0`, which do not include `v2` subdirectory, currently running `go get -u github.com/tommy-muehle/go-mnd/cmd/mnd` pulls latest `v1` version (`v1.3.0`), as it is by design with Go modules.

This may lead to confusion, as many users may user older version, without access to new features.

### Steps to reproduce the behavior

Run `go get -u github.com/tommy-muehle/go-mnd/cmd/mnd` on a fresh system.

### Go version (output of 'go version')
```
go version go1.15.3 linux/amd64
```

### Operating system / Environment
```
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```
### Expected behavior

Documented `go get -u github.com/tommy-muehle/go-mnd/cmd/mnd` and all imports should be changed to `github.com/tommy-muehle/go-mnd/v2/cmd/mnd`, including `go.mod`, so latest version is pulled.

This can be used as an example to follow: https://github.com/kubernetes/klog/commit/2bed4d00564ea4dbef273202eabb5020e97a5e1a#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6

**Comment by tommy-muehle** [comment]
@invidian Thank you very much for the report! You're totally right. I missed that. It's fixed with [this commit](https://github.com/tommy-muehle/go-mnd/commit/465f98936b93caec8a0c922b319042c31ea1cf4e) I'll soon release a new version.
