### ISSUE TITLE
Floating point one `1.0` should not be considered as magic number

### ISSUE THREAD

**Issue by renkam** [tommy-muehle/go-mnd#17]
### Short summary 
If one need to calculate multiplicative inverse `1/x` in float, then using const for `1.0` looks bad

### Steps to reproduce the behavior
```
x := 100
fraction := 1.0 / x
```

### go-mnd version or commit ref
v1.3.1-0.20200224220436-e6f9a994e8fa

### Go version (output of 'go version')
go version go1.15.3 linux/amd64

### Operating system / Environment
Debian bullseye/sid

### Expected behavior
`1.0` shouldn't be reported as magic number

### Actual behavior
`1.0` is reported as magic number

**Comment by renkam** [comment]
Same behavior is for `0.0`

**Comment by tommy-muehle** [comment]
@renkam Thanks for the report! It's fixed. I'll soon release a new version.
