### ISSUE TITLE
add ignored files will ignore all files

### ISSUE THREAD

**Issue by XyuWang** [tommy-muehle/go-mnd#23]
### Short summary 
when enable gomnd in golangci-lint
add ignore files will ignore all files
![image](https://user-images.githubusercontent.com/3951231/116205509-6c4b9300-a770-11eb-9ade-5c5e5b6b1290.png)
when excludes is blank, ignore files is `,ignores`, then will match all files
### Steps to reproduce the behavior
config:
  gomnd:
    settings:
      mnd:
        # the list of enabled checks, see https://github.com/tommy-muehle/go-mnd/#checks for description.
        checks: case,condition,operation,return
        ignored-numbers: 0,1
        ignored-functions: fanout.*,GOMAXPROCS
        ignored-files: "lexer.go"
### go-mnd version or commit ref
v2.3.2
### Go version (output of 'go version')
go1.16
### Operating system / Environment
darwin
### Expected behavior
only ignore some file
### Actual behavior
ignore all files

**Comment by XyuWang** [comment]
https://github.com/tommy-muehle/go-mnd/pull/24

**Comment by tommy-muehle** [comment]
@XyuWang 
Thanks for the report! Good catch!
