### ISSUE TITLE
Magic number in second function parameter not reported

### ISSUE THREAD

**Issue by dje29** [tommy-muehle/go-mnd#25]
### Short summary 

It seems magic number in the 2nd parameter of a function call are not reported.

### Steps to reproduce the behavior

Using this code
```
package main

import (
	"log"
)

func test1(err int) {
	log.Printf("something %d", err)
}

func test2(str string, err int) {
	log.Printf("%s %d", str, err)
}

func test3(err int, str string) {
	log.Printf("%s %d", str, err)
}

func test() int {
	test1(123)
	test2("something else", 123)
	test3(123, "another something else")
	return 123
}
```
```
go vet -vettool $(which mnd) ./test.go
```

### go-mnd version or commit ref
v1.3.0

### Go version (output of 'go version')
go version go1.14.15 linux/amd64

### Operating system / Environment
Linux Ubuntu 18.04, but case is reproducible with docker image too

```
docker run --rm -v "$PWD":/app -w /app tommymuehle/go-mnd:latest ./test.go
/app/test.go:20:8: Magic number: 123, in <argument> detected
/app/test.go:22:8: Magic number: 123, in <argument> detected
/app/test.go:23:9: Magic number: 123, in <return> detected
```

### Expected behavior
The Magic number on line 21 should be reported:
```
test2("something else", 123)
```

### Actual behavior
The Magic numbers are reported for other cases but not for magic number in 2nd function parameter.

**Comment by tommy-muehle** [comment]
@dje29 
Thanks for the report! I could reproduce the behaviour. And unfortunately the README isn't up to date. Please use
```
go get -u github.com/tommy-muehle/go-mnd/v2/cmd/mnd
```
to get the latest version.
