### ISSUE TITLE
How to add additional numbers to the ignore list?

### ISSUE THREAD

**Issue by bishtawi** [tommy-muehle/go-mnd#3]
According to the readme, by default 0 is excluded. How do we exclude other numbers? I would like to add `1` to be excluded.

**Comment by tommy-muehle** [comment]
Hi @bishtawi,

currently that's not possible. But that would be a nice addition. I'll implement it soon.

**Comment by vitalyisaev2** [comment]
This feature is really essential. Without it I just have to disable the whole linter, because `1` is often used in cycles.

**Comment by tommy-muehle** [comment]
@vitalyisaev2 
I'll release it today. :) But can you please provide an example for the case you mentioned? Maybe I can exclude it by default.

**Comment by tommy-muehle** [comment]
@bishtawi 
It's implemented. Please checkout the new version v1.2.0 :)

**Comment by vitalyisaev2** [comment]
@tommy-muehle thanks for the quick implementation of this feature!

Regarding to the cases where `1` should not be considered as a magic number, pl

Custom `for` loop:
```go
        // custom for loop
	for i, itemID := range ring {
		next := i + 1
		start := int(itemID)%ring.totalItems - 1

		if start < 0 {
			start += step
		}

                // ...
```

Branching based on `int` value evaluation:
```go
    func computeResult(value int) ([][]int, error) {
	if subsets == 0 {
		return nil, fmt.Errorf("invalid value: 0")
	}

	if subsets == 1 {
		return [][]int{{255}}, nil
	}

       // more complicated logic for other cases
```
